# Generated by Django 4.1.7 on 2023-03-29 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='product_imgs/')),
                ('slug', models.CharField(max_length=400)),
                ('detail', models.TextField()),
                ('specs', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.color')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.marca')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.size')),
            ],
        ),
    ]
